# -*- coding: utf-8 -*-

SMS_CAPTCHA = 'SMS_CAPTCHA'
SMS_CAPTCHA_SENT = 'SMS_CAPTCHA_SENT'
IMAGE_CAPTCHA = 'IMAGE_CAPTCHA'
IMAGE_CAPTCHA_CODE = 'IMAGE_CAPTCHA_CODE'
CONFIRM_EMAIL = 'CONFIRM_EMAIL'

REGISTER_ACTION = 'REGISTER'
RESET_PASSWORD_ACTION = 'RESET_PASSWORD'

USER_REGISTER_STEP_DONE = 'USER_REGISTER_STEP_DONE'
USER_REGISTER_MOBILE = 'USER_REGISTER_MOBILE'
USER_REGISTER_EMAIL = 'USER_REGISTER_EMAIL'

VENDOR_REGISTER_STEP_DONE = 'VENDOR_REGISTER_STEP_DONE'
VENDOR_REGISTER_MOBILE = 'VENDOR_REGISTER_MOBILE'

DISTRIBUTOR_REGISTER = 'DISTRIBUTOR_REGISTER'
