# -*- coding: utf-8 -*-

SMS_CAPTCHA = 'SMS_CAPTCHA'
SMS_CAPTCHA_SENT = 'SMS_CAPTCHA_SENT'
IMAGE_CAPTCHA = 'IMAGE_CAPTCHA'
CONFIRM_EMAIL = 'CONFIRM_EMAIL'

REGISTER_ACTION = 'REGISTER'
RESET_PASSWORD_ACTION = 'RESET_PASSWORD'