"""empty message

Revision ID: 1364179233d
Revises: 509ab855a76
Create Date: 2015-12-22 16:27:57.401922

"""

# revision identifiers, used by Alembic.
revision = '1364179233d'
down_revision = '509ab855a76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carve_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carve_type', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('items', sa.Column('carve_type_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'carve_type_id')
    op.drop_table('carve_types')
    ### end Alembic commands ###
