"""empty message

Revision ID: 161013d57ac
Revises: 27683fa636e
Create Date: 2015-12-21 21:15:47.783514

"""

# revision identifiers, used by Alembic.
revision = '161013d57ac'
down_revision = '27683fa636e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.drop_table('provinces')
    op.drop_table('districts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cn_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('district', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('provinces',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cn_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('province', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cities',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cn_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('city', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('province_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
