"""empty message

Revision ID: 16e0938bea1
Revises: 302144044fa
Create Date: 2015-08-17 21:23:41.690791

"""

# revision identifiers, used by Alembic.
revision = '16e0938bea1'
down_revision = '302144044fa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_carves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('carve_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('items', 'carve_id')
    op.create_unique_constraint(None, 'vendors', ['mobile'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.add_column('items', sa.Column('carve_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_table('item_carves')
    ### end Alembic commands ###
