"""empty message

Revision ID: 1710939eea6
Revises: 2404c417485
Create Date: 2015-07-19 23:59:01.127027

"""

# revision identifiers, used by Alembic.
revision = '1710939eea6'
down_revision = '2404c417485'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'license_limit')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('license_limit', sa.Integer(), nullable=False))
    ### end Alembic commands ###
