"""empty message

Revision ID: 18d86936565
Revises: None
Create Date: 2015-09-19 17:14:30.743146

"""

# revision identifiers, used by Alembic.
revision = '18d86936565'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carve', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Unicode(length=20), nullable=False),
    sa.Column('father_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.Unicode(length=15), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decorations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decoration', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributor_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Unicode(length=30), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributor_revocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('contract', sa.String(length=255), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=20), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=30), nullable=False),
    sa.Column('contact_telephone', sa.String(length=30), nullable=False),
    sa.Column('contact_mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('contact', sa.Unicode(length=10), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('district', sa.Unicode(length=15), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('first_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_material', sa.Unicode(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('first_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_scene', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_carves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('carve_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('filename', sa.Unicode(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_tenons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tenon_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Unicode(length=20), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.Column('second_material_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(length=10), nullable=False),
    sa.Column('width', sa.String(length=10), nullable=False),
    sa.Column('height', sa.String(length=10), nullable=False),
    sa.Column('area', sa.String(length=10), nullable=False),
    sa.Column('stove_id', sa.Integer(), nullable=False),
    sa.Column('outside_sand_id', sa.Integer(), nullable=False),
    sa.Column('inside_sand_id', sa.Integer(), nullable=False),
    sa.Column('paint_id', sa.Integer(), nullable=False),
    sa.Column('decoration_id', sa.Integer(), nullable=False),
    sa.Column('second_scene_id', sa.Integer(), nullable=False),
    sa.Column('story', sa.Unicode(length=5000), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('searchable', sa.Boolean(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_suite', sa.Boolean(), nullable=False),
    sa.Column('is_component', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_address_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('deposit', sa.Integer(), nullable=False),
    sa.Column('deposit_payed', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_payed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paint', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privileges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('province', sa.Unicode(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sand', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('second_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_material_id', sa.Integer(), nullable=False),
    sa.Column('second_material', sa.Unicode(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('second_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_scene_id', sa.Integer(), nullable=False),
    sa.Column('second_scene', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stoves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stove', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenon', sa.Unicode(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Unicode(length=30), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.Unicode(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('vendor_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Unicode(length=30), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('agent_name', sa.Unicode(length=10), nullable=False),
    sa.Column('agent_identity', sa.CHAR(length=18), nullable=False),
    sa.Column('agent_identity_front', sa.String(length=255), nullable=False),
    sa.Column('agent_identity_back', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Unicode(length=30), nullable=False),
    sa.Column('license_limit', sa.CHAR(length=10), nullable=False),
    sa.Column('license_image', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=30), nullable=False),
    sa.Column('telephone', sa.CHAR(length=15), nullable=False),
    sa.Column('introduction', sa.Unicode(length=30), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_time', sa.Integer(), nullable=False),
    sa.Column('reject_message', sa.Unicode(length=100), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('initialized', sa.Boolean(), nullable=False),
    sa.Column('item_permission', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors')
    op.drop_table('vendor_addresses')
    op.drop_table('users')
    op.drop_table('user_addresses')
    op.drop_table('tenons')
    op.drop_table('stoves')
    op.drop_table('stocks')
    op.drop_table('second_scenes')
    op.drop_table('second_materials')
    op.drop_table('sands')
    op.drop_table('provinces')
    op.drop_table('privileges')
    op.drop_table('paints')
    op.drop_table('orders')
    op.drop_table('materials')
    op.drop_table('items')
    op.drop_table('item_tenons')
    op.drop_table('item_images')
    op.drop_table('item_carves')
    op.drop_table('first_scenes')
    op.drop_table('first_materials')
    op.drop_table('districts')
    op.drop_table('distributors')
    op.drop_table('distributor_revocations')
    op.drop_table('distributor_addresses')
    op.drop_table('decorations')
    op.drop_table('collections')
    op.drop_table('cities')
    op.drop_table('categories')
    op.drop_table('carves')
    ### end Alembic commands ###
