"""empty message

Revision ID: 1d648ebfac5
Revises: 36d42492609
Create Date: 2015-07-18 20:29:23.452678

"""

# revision identifiers, used by Alembic.
revision = '1d648ebfac5'
down_revision = '36d42492609'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'first_scene_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('first_scene_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    ### end Alembic commands ###
