"""empty message

Revision ID: 2033c482ff
Revises: 58764999798
Create Date: 2015-10-11 17:00:55.905817

"""

# revision identifiers, used by Alembic.
revision = '2033c482ff'
down_revision = '58764999798'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor_addresses', sa.Column('latitude', sa.Float(precision=32), nullable=False))
    op.add_column('distributor_addresses', sa.Column('longitude', sa.Float(precision=32), nullable=False))
    op.add_column('user_addresses', sa.Column('latitude', sa.Float(precision=32), nullable=False))
    op.add_column('user_addresses', sa.Column('longitude', sa.Float(precision=32), nullable=False))
    op.add_column('vendor_addresses', sa.Column('latitude', sa.Float(precision=32), nullable=False))
    op.add_column('vendor_addresses', sa.Column('longitude', sa.Float(precision=32), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_addresses', 'longitude')
    op.drop_column('vendor_addresses', 'latitude')
    op.drop_column('user_addresses', 'longitude')
    op.drop_column('user_addresses', 'latitude')
    op.drop_column('distributor_addresses', 'longitude')
    op.drop_column('distributor_addresses', 'latitude')
    ### end Alembic commands ###
