"""empty message

Revision ID: 27683fa636e
Revises: b71226bcda
Create Date: 2015-12-21 15:50:33.277196

"""

# revision identifiers, used by Alembic.
revision = '27683fa636e'
down_revision = 'b71226bcda'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guide_sms')
    ### end Alembic commands ###
