"""empty message

Revision ID: 2827c4247fe
Revises: 16e0938bea1
Create Date: 2015-09-07 09:36:42.204066

"""

# revision identifiers, used by Alembic.
revision = '2827c4247fe'
down_revision = '16e0938bea1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.Unicode(length=30), nullable=False))
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=20), nullable=False))
    op.create_index('username', 'users', ['username'], unique=True)
    op.drop_column('users', 'nickname')
    ### end Alembic commands ###
