"""empty message

Revision ID: 2972fe1b853
Revises: 300d11229ca
Create Date: 2015-07-18 12:46:27.746266

"""

# revision identifiers, used by Alembic.
revision = '2972fe1b853'
down_revision = '300d11229ca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('agent_identity', sa.CHAR(length=18), nullable=False))
    op.add_column('vendors', sa.Column('agent_identity_back', sa.String(length=255), nullable=False))
    op.add_column('vendors', sa.Column('agent_identity_front', sa.String(length=255), nullable=False))
    op.add_column('vendors', sa.Column('agent_name', sa.Unicode(length=10), nullable=False))
    op.drop_column('vendors', 'legal_person_identity')
    op.drop_column('vendors', 'legal_person_name')
    op.drop_column('vendors', 'legal_person_identity_back')
    op.drop_column('vendors', 'legal_person_identity_front')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('legal_person_identity_front', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('vendors', sa.Column('legal_person_identity_back', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('vendors', sa.Column('legal_person_name', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('vendors', sa.Column('legal_person_identity', mysql.CHAR(length=18), nullable=False))
    op.drop_column('vendors', 'agent_name')
    op.drop_column('vendors', 'agent_identity_front')
    op.drop_column('vendors', 'agent_identity_back')
    op.drop_column('vendors', 'agent_identity')
    ### end Alembic commands ###
