"""empty message

Revision ID: 300d11229ca
Revises: 5a7b26aa354
Create Date: 2015-07-17 00:39:44.170140

"""

# revision identifiers, used by Alembic.
revision = '300d11229ca'
down_revision = '5a7b26aa354'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_scene', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('second_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_scene_id', sa.Integer(), nullable=False),
    sa.Column('second_scene', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('categories')
    op.add_column('items', sa.Column('first_scene_id', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('second_scene_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'second_scene_id')
    op.drop_column('items', 'first_scene_id')
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('second_scenes')
    op.drop_table('first_scenes')
    ### end Alembic commands ###
