"""empty message

Revision ID: 314897e4065
Revises: 64049abfc2
Create Date: 2015-10-10 21:15:26.266560

"""

# revision identifiers, used by Alembic.
revision = '314897e4065'
down_revision = '64049abfc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_index('mobile', table_name='users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('mobile', 'users', ['mobile'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    ### end Alembic commands ###
