"""empty message

Revision ID: 3184e9b442f
Revises: 3d7b863226e
Create Date: 2015-10-07 04:12:02.691066

"""

# revision identifiers, used by Alembic.
revision = '3184e9b442f'
down_revision = '3d7b863226e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.Unicode(length=15), nullable=False),
    sa.Column('father_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('pinyin', sa.String(length=30), nullable=False),
    sa.Column('pinyin_index', sa.CHAR(length=1), nullable=False),
    sa.Column('distributor_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('areas')
    ### end Alembic commands ###
