"""empty message

Revision ID: 321a13bd8ee
Revises: 3863da26138
Create Date: 2015-07-07 21:29:35.064433

"""

# revision identifiers, used by Alembic.
revision = '321a13bd8ee'
down_revision = '3863da26138'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor_revocations', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    op.add_column('distributor_revocations', sa.Column('pending', sa.Boolean(), nullable=False))
    op.drop_column('distributor_revocations', 'revocation_message')
    op.drop_column('vendors', 'address_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('address_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('distributor_revocations', sa.Column('revocation_message', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('distributor_revocations', 'pending')
    op.drop_column('distributor_revocations', 'is_revoked')
    ### end Alembic commands ###
