"""empty message

Revision ID: 333b55f8e9c
Revises: 314897e4065
Create Date: 2015-10-11 13:55:29.076968

"""

# revision identifiers, used by Alembic.
revision = '333b55f8e9c'
down_revision = '314897e4065'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor_addresses', sa.Column('poi_id', sa.Integer(), nullable=False))
    op.add_column('user_addresses', sa.Column('poi_id', sa.Integer(), nullable=False))
    op.add_column('vendor_addresses', sa.Column('poi_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_addresses', 'poi_id')
    op.drop_column('user_addresses', 'poi_id')
    op.drop_column('distributor_addresses', 'poi_id')
    ### end Alembic commands ###
