"""empty message

Revision ID: 3551e90bff4
Revises: 2033c482ff
Create Date: 2015-10-13 22:21:12.730217

"""

# revision identifiers, used by Alembic.
revision = '3551e90bff4'
down_revision = '2033c482ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('style', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vendors', sa.Column('brand', sa.Unicode(length=10), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'brand')
    op.drop_table('styles')
    ### end Alembic commands ###
