"""empty message

Revision ID: 36d42492609
Revises: 3136e86872b
Create Date: 2015-07-18 20:03:37.641516

"""

# revision identifiers, used by Alembic.
revision = '36d42492609'
down_revision = '3136e86872b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_categories')
    op.drop_column('materials', 'material_category_id')
    op.drop_column('materials', 'origin')
    op.drop_column('materials', 'alias')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('alias', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('materials', sa.Column('origin', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('materials', sa.Column('material_category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_table('material_categories',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('material_category', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
