"""empty message

Revision ID: 3863da26138
Revises: cc4e912006
Create Date: 2015-06-25 21:02:01.966297

"""

# revision identifiers, used by Alembic.
revision = '3863da26138'
down_revision = 'cc4e912006'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributor_revocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('revocation_message', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('email', table_name='privileges')
    op.drop_index('email', table_name='users')
    op.add_column('vendors', sa.Column('confirmed_time', sa.Integer(), nullable=False))
    op.add_column('vendors', sa.Column('reject_message', sa.Unicode(length=100), nullable=False))
    op.add_column('vendors', sa.Column('rejected', sa.Boolean(), nullable=False))
    op.drop_index('email', table_name='vendors')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'vendors', ['email'], unique=True)
    op.drop_column('vendors', 'rejected')
    op.drop_column('vendors', 'reject_message')
    op.drop_column('vendors', 'confirmed_time')
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_index('email', 'privileges', ['email'], unique=True)
    op.drop_table('distributor_revocations')
    ### end Alembic commands ###
