"""empty message

Revision ID: 3f46fe4e131
Revises: 1710939eea6
Create Date: 2015-07-20 00:10:36.064975

"""

# revision identifiers, used by Alembic.
revision = '3f46fe4e131'
down_revision = '1710939eea6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('license_limit', sa.CHAR(length=10), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'license_limit')
    ### end Alembic commands ###
