"""empty message

Revision ID: 4518fd2ec25
Revises: 5abd389515d
Create Date: 2015-11-30 11:14:12.853393

"""

# revision identifiers, used by Alembic.
revision = '4518fd2ec25'
down_revision = '5abd389515d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributors', sa.Column('ext_number', sa.CHAR(length=10), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributors', 'ext_number')
    ### end Alembic commands ###
