"""empty message

Revision ID: 476640e2878
Revises: 161013d57ac
Create Date: 2015-12-21 21:18:44.218259

"""

# revision identifiers, used by Alembic.
revision = '476640e2878'
down_revision = '161013d57ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('second_scenes')
    op.drop_table('first_scenes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_scenes',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_scene', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('second_scenes',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_scene_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('second_scene', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
