"""empty message

Revision ID: 4b906e74941
Revises: b2f9c8b317
Create Date: 2015-07-19 13:48:55.945631

"""

# revision identifiers, used by Alembic.
revision = '4b906e74941'
down_revision = 'b2f9c8b317'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('contact', sa.String(length=30), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'contact')
    ### end Alembic commands ###
