"""empty message

Revision ID: 509ab855a76
Revises: 476640e2878
Create Date: 2015-12-22 13:47:39.020687

"""

# revision identifiers, used by Alembic.
revision = '509ab855a76'
down_revision = '476640e2878'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_father_id'), 'categories', ['father_id'], unique=False)
    op.create_index(op.f('ix_collections_item_id'), 'collections', ['item_id'], unique=False)
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_index(op.f('ix_distributor_addresses_distributor_id'), 'distributor_addresses', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_distributors_vendor_id'), 'distributors', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_is_component'), 'items', ['is_component'], unique=False)
    op.create_index(op.f('ix_items_is_deleted'), 'items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_items_scene_id'), 'items', ['scene_id'], unique=False)
    op.create_index(op.f('ix_items_second_material_id'), 'items', ['second_material_id'], unique=False)
    op.create_index(op.f('ix_items_style_id'), 'items', ['style_id'], unique=False)
    op.create_index(op.f('ix_items_vendor_id'), 'items', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_stocks_distributor_id'), 'stocks', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_stocks_item_id'), 'stocks', ['item_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_item_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_distributor_id'), table_name='stocks')
    op.drop_index(op.f('ix_items_vendor_id'), table_name='items')
    op.drop_index(op.f('ix_items_style_id'), table_name='items')
    op.drop_index(op.f('ix_items_second_material_id'), table_name='items')
    op.drop_index(op.f('ix_items_scene_id'), table_name='items')
    op.drop_index(op.f('ix_items_is_deleted'), table_name='items')
    op.drop_index(op.f('ix_items_is_component'), table_name='items')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_index(op.f('ix_distributors_vendor_id'), table_name='distributors')
    op.drop_index(op.f('ix_distributor_addresses_distributor_id'), table_name='distributor_addresses')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_item_id'), table_name='collections')
    op.drop_index(op.f('ix_categories_father_id'), table_name='categories')
    ### end Alembic commands ###
