"""empty message

Revision ID: 581aad2a947
Revises: 4b906e74941
Create Date: 2015-07-19 14:29:55.784863

"""

# revision identifiers, used by Alembic.
revision = '581aad2a947'
down_revision = '4b906e74941'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_images', sa.Column('filename', sa.Unicode(length=30), nullable=False))
    op.add_column('item_images', sa.Column('hash', sa.String(length=32), nullable=False))
    op.add_column('item_images', sa.Column('path', sa.String(length=255), nullable=False))
    op.drop_column('item_images', 'image')
    op.drop_column('item_images', 'image_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_images', sa.Column('image_hash', mysql.VARCHAR(length=32), nullable=False))
    op.add_column('item_images', sa.Column('image', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('item_images', 'path')
    op.drop_column('item_images', 'hash')
    op.drop_column('item_images', 'filename')
    ### end Alembic commands ###
