"""empty message

Revision ID: 5a7b26aa354
Revises: None
Create Date: 2015-07-16 00:39:31.988812

"""

# revision identifiers, used by Alembic.
revision = '5a7b26aa354'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carve', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.Unicode(length=15), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decorations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decoration', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributor_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Unicode(length=30), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributor_revocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=20), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=30), nullable=False),
    sa.Column('contact_mobile', sa.String(length=30), nullable=False),
    sa.Column('contact_telephone', sa.String(length=30), nullable=False),
    sa.Column('contact', sa.Unicode(length=10), nullable=False),
    sa.Column('deleted_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('district', sa.Unicode(length=15), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('first_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_category', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('image_hash', sa.String(length=32), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_tenons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tenon_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Unicode(length=20), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('second_category_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('stove_id', sa.Integer(), nullable=False),
    sa.Column('carve_id', sa.Integer(), nullable=False),
    sa.Column('sand_id', sa.Integer(), nullable=False),
    sa.Column('paint_id', sa.Integer(), nullable=False),
    sa.Column('decoration_id', sa.Integer(), nullable=False),
    sa.Column('story', sa.Unicode(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_category', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_category_id', sa.Integer(), nullable=False),
    sa.Column('material', sa.Unicode(length=10), nullable=False),
    sa.Column('alias', sa.Unicode(length=20), nullable=False),
    sa.Column('origin', sa.Unicode(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_address_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('deposit', sa.Integer(), nullable=False),
    sa.Column('deposit_payed', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_payed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paint', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privileges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('province', sa.Unicode(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sand', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('second_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('second_category', sa.Unicode(length=10), nullable=False),
    sa.Column('first_category_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stoves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stove', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenon', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Unicode(length=30), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendor_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Unicode(length=30), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('legal_person_name', sa.Unicode(length=10), nullable=False),
    sa.Column('legal_person_identity', sa.CHAR(length=18), nullable=False),
    sa.Column('legal_person_identity_front', sa.String(length=255), nullable=False),
    sa.Column('legal_person_identity_back', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Unicode(length=30), nullable=False),
    sa.Column('license_limit', sa.Integer(), nullable=False),
    sa.Column('license_long_time_limit', sa.Boolean(), nullable=False),
    sa.Column('license_image', sa.String(length=255), nullable=False),
    sa.Column('contact_mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('contact_telephone', sa.CHAR(length=15), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_time', sa.Integer(), nullable=False),
    sa.Column('reject_message', sa.Unicode(length=100), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors')
    op.drop_table('vendor_addresses')
    op.drop_table('users')
    op.drop_table('user_addresses')
    op.drop_table('tenons')
    op.drop_table('stoves')
    op.drop_table('stocks')
    op.drop_table('second_categories')
    op.drop_table('sands')
    op.drop_table('provinces')
    op.drop_table('privileges')
    op.drop_table('paints')
    op.drop_table('orders')
    op.drop_table('materials')
    op.drop_table('material_categories')
    op.drop_table('items')
    op.drop_table('item_tenons')
    op.drop_table('item_images')
    op.drop_table('item_categories')
    op.drop_table('first_categories')
    op.drop_table('districts')
    op.drop_table('distributors')
    op.drop_table('distributor_revocations')
    op.drop_table('distributor_addresses')
    op.drop_table('decorations')
    op.drop_table('collections')
    op.drop_table('cities')
    op.drop_table('categories')
    op.drop_table('carves')
    ### end Alembic commands ###
