"""empty message

Revision ID: 64049abfc2
Revises: 3184e9b442f
Create Date: 2015-10-08 13:04:22.707789

"""

# revision identifiers, used by Alembic.
revision = '64049abfc2'
down_revision = '3184e9b442f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_areas_cn_id'), 'areas', ['cn_id'], unique=False)
    op.create_index(op.f('ix_areas_father_id'), 'areas', ['father_id'], unique=False)
    op.add_column('distributor_addresses', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('distributor_addresses', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('user_addresses', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('user_addresses', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('vendor_addresses', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('vendor_addresses', sa.Column('longitude', sa.Float(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_addresses', 'longitude')
    op.drop_column('vendor_addresses', 'latitude')
    op.drop_column('user_addresses', 'longitude')
    op.drop_column('user_addresses', 'latitude')
    op.drop_column('distributor_addresses', 'longitude')
    op.drop_column('distributor_addresses', 'latitude')
    op.drop_index(op.f('ix_areas_father_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_cn_id'), table_name='areas')
    ### end Alembic commands ###
