"""empty message

Revision ID: aa3ccaf776
Revises: b27662990a
Create Date: 2015-08-03 21:22:47.453499

"""

# revision identifiers, used by Alembic.
revision = 'aa3ccaf776'
down_revision = 'b27662990a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributors', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    op.add_column('privileges', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed')
    op.drop_column('privileges', 'email_confirmed')
    op.drop_column('distributors', 'email_confirmed')
    ### end Alembic commands ###
