"""empty message

Revision ID: b27662990a
Revises: 5af2141b7a6
Create Date: 2015-07-24 21:19:59.685638

"""

# revision identifiers, used by Alembic.
revision = 'b27662990a'
down_revision = '5af2141b7a6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributors', sa.Column('contact_mobile', sa.CHAR(length=11), nullable=False))
    op.add_column('distributors', sa.Column('contact_telephone', sa.String(length=30), nullable=False))
    op.drop_column('distributors', 'telephone')
    op.drop_column('distributors', 'mobile')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributors', sa.Column('mobile', mysql.CHAR(length=11), nullable=False))
    op.add_column('distributors', sa.Column('telephone', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('distributors', 'contact_telephone')
    op.drop_column('distributors', 'contact_mobile')
    ### end Alembic commands ###
