"""empty message

Revision ID: b2f9c8b317
Revises: 1d648ebfac5
Create Date: 2015-07-19 02:12:42.801242

"""

# revision identifiers, used by Alembic.
revision = 'b2f9c8b317'
down_revision = '1d648ebfac5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('introduction', sa.Unicode(length=30), nullable=False))
    op.drop_column('vendors', 'license_long_time_limit')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('license_long_time_limit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('vendors', 'introduction')
    ### end Alembic commands ###
