"""empty message

Revision ID: b71226bcda
Revises: 4518fd2ec25
Create Date: 2015-12-17 16:25:47.454003

"""

# revision identifiers, used by Alembic.
revision = 'b71226bcda'
down_revision = '4518fd2ec25'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Unicode(length=200), nullable=False),
    sa.Column('contact', sa.Unicode(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_cn_id'), 'areas', ['cn_id'], unique=False)
    op.create_index(op.f('ix_areas_father_id'), 'areas', ['father_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_areas_father_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_cn_id'), table_name='areas')
    op.drop_table('feedbacks')
    ### end Alembic commands ###
